// Datos de ejemplo de películas
/* const movies = [
    { title: "Toy Story 4", image: "https://cdn11.bigcommerce.com/s-ydriczk/images/stencil/1500x1500/products/88996/93194/Toy-Story-4-FInal-Style-Poster-buy-original-movie-posters-at-starstills__38785.1563972734.jpg?c=2&imbypass=on" },
    { title: "Home Alone", image: "https://cdn.shopify.com/s/files/1/1057/4964/products/Home-Alone-Vintage-Movie-Poster-Original_866d9d28_368x.jpg?v=1741732804" },
    { title: "Back to the Future", image: "https://imgc.allpostersimages.com/img/posters/back-to-the-future-1985-directed-by-robert-zemeckis_u-l-q1h92310.jpg" },
    { title: "Jurassic Pack", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9eNbn7bQf47k_r2h3zS32lWJwKMIWhpBa8A&s" },
    { title: "Terminator 2", image: "https://s3-eu-west-1.amazonaws.com/entertainmentie/uploads/2016/04/03140937/terminator-2-french-movie-poster-15x21-91-schwarzenegger-james-cameron-e1549203082175.jpg" },
    { title: "The Dark Knight", image: "https://www.kwikkopy.com.au/wp-content/uploads/2014/11/The-Dark-Knight.jpg" },
    { title: "Home Alone 2", image: "https://lumiere-a.akamaihd.net/v1/images/image_ed8d7a4e.jpeg?region=0%2C0%2C800%2C1200" },
]; */
const moviesMock = [
    { title: "John Wick", image: "https://m.media-amazon.com/images/I/71i6JuSZUGL.jpg", genres: ["Acción", "Thriller"] },
    { title: "Mad Max: Fury Road", image: "https://angelusnews.com/wp-content/uploads/2019/09/4uicq6hz9e_Movies_mad_max.jpg", genres: ["Acción", "Ciencia Ficción"] },
    { title: "The Dark Knight", image: "https://www.kwikkopy.com.au/wp-content/uploads/2014/11/The-Dark-Knight.jpg", genres: ["Acción", "Crimen"] },
    { title: "Skyfall", image: "https://artofthemovies.co.uk/cdn/shop/files/IMG_7829_720x@2x.jpg?v=1723206212", genres: ["Acción", "Thriller"] },
    { title: "The Matrix", image: "https://cdn-images.dzcdn.net/images/cover/7f18600ed057cda07b4bcb4eecb83cb5/0x1900-000000-80-0-0.jpg", genres: ["Acción", "Ciencia Ficción"] },
    { title: "Mission: Impossible", image: "https://i.ebayimg.com/images/g/9M8AAOSwyuVd8Ss7/s-l400.jpg", genres: ["Acción", "Aventura"] },
    { title: "Gladiator", image: "https://m.media-amazon.com/images/I/61U6R6U6KEL._AC_UF894,1000_QL80_.jpg", genres: ["Acción", "Drama"] },
    { title: "Kill Bill", image: "https://musicart.xboxlive.com/7/1c400700-0000-0000-0000-000000000002/504/image.jpg", genres: ["Acción", "Thriller"] },
    { title: "The Avengers", image: "https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_.jpg", genres: ["Acción", "Ciencia Ficción"] },
    { title: "Black Panther", image: "https://m.media-amazon.com/images/I/81dae9nZFBS.jpg", genres: ["Acción", "Aventura"] },
    //     { title: "The Bourne Identity", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Acción", "Thriller"] },
    //     { title: "300", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Acción", "Histórica"] },
    //     { title: "Terminator 2", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Acción", "Ciencia Ficción"] },
    //     { title: "Fast & Furious 7", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Acción", "Aventura"] },

    //     { title: "Superbad", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Adolescente"] },
    //     { title: "The Hangover", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Aventura"] },
    //     { title: "Bridesmaids", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Romance"] },
    //     { title: "Dumb and Dumber", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Aventura"] },
    //     { title: "Anchorman", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Parodia"] },
    //     { title: "Ted", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Fantasía"] },
    //     { title: "Ghostbusters", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Ciencia Ficción"] },
    //     { title: "Groundhog Day", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Fantasía"] },
    //     { title: "The Grand Budapest Hotel", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Drama"] },
    //     { title: "Zoolander", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Parodia"] },
    //     { title: "Airplane!", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Parodia"] },
    //     { title: "The Mask", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Fantasía"] },
    //     { title: "Mrs. Doubtfire", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Drama"] },
    //     { title: "Deadpool", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Comedia", "Acción"] },

    //     { title: "The Shawshank Redemption", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Crimen"] },
    //     { title: "The Godfather", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Crimen"] },
    //     { title: "Forrest Gump", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Romance"] },
    //     { title: "Schindler's List", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Histórica"] },
    //     { title: "Fight Club", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Thriller"] },
    //     { title: "The Social Network", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Biografía"] },
    //     { title: "Good Will Hunting", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Romance"] },
    //     { title: "The Pursuit of Happyness", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Biografía"] },
    //     { title: "A Beautiful Mind", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Biografía"] },
    //     { title: "The Green Mile", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Fantasía"] },
    //     { title: "The Pianist", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Histórica"] },
    //     { title: "12 Years a Slave", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Histórica"] },
    //     { title: "The Revenant", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Aventura"] },
    //     { title: "Parasite", image: "https://m.media-amazon.com/images/I/71Q4hVqA+5L._AC_UF1000,1000_QL80_.jpg", genres: ["Drama", "Thriller"] }
];
export { moviesMock };